#!/bin/bash

mkdir -p roles/linux-docker/{tasks,templates}
mkdir -p roles/windows/{tasks,files}

touch ansible.cfg
touch inventory.yml
touch playbook.yml
touch roles/linux-docker/tasks/main.yml
touch roles/linux-docker/templates/docker-compose.yml.j2
touch roles/windows/tasks/main.yml
touch roles/windows/files/promtail-config.yml
touch roles/windows/files/promtail.ps1

echo "Estructura de subdirectorios y archivos creada en el directorio actual."
